branches:
  only:
  - master

language: node_js

node_js:
  - "9.9.0"
  - "lts/*"

notifications:
  slack: $SLACK_STRING

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g typescript

script:
  - npm test

after_success:
  - npm run coverage

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_ALREADY_RUN" ]; then
      export BEFORE_DEPLOY_ALREADY_RUN=1;
      git tag "$(cat VERSION)";
      npm install --production
      npm run prepublishOnly
    fi

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    skip_cleanup: true
    on:
      node: '9.9.0'
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: v$(cat VERSION)
    skip_cleanup: true
    on:
      node: '9.9.0'